/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restosalero2;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import static java.util.random.RandomGeneratorFactory.all;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 058 Ernika Frevita Ayu Septiani
 *         051 Sefni Marcella 
 *         PTI B 2022
 */
public class Kasir extends javax.swing.JFrame {
String pilihan = "";
    int Harga_makanan;
    int Harga_minuman;
    int Harga_snack;
    int Jumlah_minuman;
    int bayar, beli, Harga;
    private int all;
    /**
     * Creates new form Kasir
     */
    String NamaPelanggan;
    String Nomeja;
    String DT;
    String Makanan;
    String HargaMakanan;
    String JumlahMakanan;
    String Minuman;
    String HargaMinuman;
    String JumlahMinuman;
    String Snack;
    String HargaSnack;
    String JumlahSnack;
    String TotalHarga;
    String Tunai;
    String Kembali;
    String Pembayaran;
    String Table;
    String Metode;
    
    public Kasir() {
        initComponents();
    }
    
private void TotalHarga(){
        int sub_total = 0;
        for (int i = 0; i<tabelpesanan.getRowCount(); i++){
            sub_total+= Integer.parseInt((String) tabelpesanan.getValueAt(i,4).toString().replace(".",""));
        }
        total.setText(nf.Format(sub_total));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namapel = new javax.swing.JTextField();
        nomeja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namamakanan = new javax.swing.JComboBox<>();
        hrgmakanan = new javax.swing.JTextField();
        jmlhmakanan = new javax.swing.JTextField();
        btntambahmakan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nmminuman = new javax.swing.JComboBox<>();
        hrgminuman = new javax.swing.JTextField();
        jmlhminuman = new javax.swing.JTextField();
        btntambahminum = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nmsnack = new javax.swing.JComboBox<>();
        hrgsnack = new javax.swing.JTextField();
        jmlhsnack = new javax.swing.JTextField();
        btntambahsnack = new javax.swing.JButton();
        DineIn = new javax.swing.JCheckBox();
        takeaway = new javax.swing.JCheckBox();
        btnhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpesanan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ttltunai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ttlkembali = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pembayaran = new javax.swing.JComboBox<>();
        btnjumlah = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        metode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("DAFTAR MENU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nomor Meja :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nama Pelanggan :");

        namapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapelActionPerformed(evt);
            }
        });

        nomeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomejaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Makanan :");

        namamakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Nasi Pecel", "Nasi Campur", "Ayam Geprek", "Nasi Padang", "Rendang", " " }));
        namamakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namamakananActionPerformed(evt);
            }
        });

        hrgmakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgmakananActionPerformed(evt);
            }
        });

        jmlhmakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlhmakananActionPerformed(evt);
            }
        });

        btntambahmakan.setText("Tambah");
        btntambahmakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahmakanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Minuman :");

        nmminuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Es Jeruk", "Es Campur", "Es Teh", "Kopi", "Teh Hangat", " " }));
        nmminuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmminumanActionPerformed(evt);
            }
        });

        hrgminuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgminumanActionPerformed(evt);
            }
        });

        jmlhminuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlhminumanActionPerformed(evt);
            }
        });

        btntambahminum.setText("Tambah");
        btntambahminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahminumActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Snack :");

        nmsnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Lontong", "Kerupuk", "Peyek" }));
        nmsnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmsnackActionPerformed(evt);
            }
        });

        hrgsnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgsnackActionPerformed(evt);
            }
        });

        jmlhsnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlhsnackActionPerformed(evt);
            }
        });

        btntambahsnack.setText("Tambah");
        btntambahsnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahsnackActionPerformed(evt);
            }
        });

        DineIn.setText("Dine In");
        DineIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DineInActionPerformed(evt);
            }
        });

        takeaway.setText("Takeaway");
        takeaway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeawayActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jScrollPane1.setToolTipText("thk");

        tabelpesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama ", "Jumlah", "Harga", "Total"
            }
        ));
        jScrollPane1.setViewportView(tabelpesanan);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Total Harga");

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tunai :");

        ttltunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttltunaiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Kembalian :");

        ttlkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttlkembaliActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Metode Pembayaran :");

        pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Cash", "Debit", "Qris" }));
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });

        btnjumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnjumlah.setText("Jumlah");
        btnjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjumlahActionPerformed(evt);
            }
        });

        btncetak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncetak.setText("Cetak");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Metode Pesanan:");

        metode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namamakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hrgsnack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jmlhminuman, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btntambahminum)
                                    .addComponent(jmlhsnack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btntambahsnack)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnhapus))
                                    .addComponent(btntambahmakan)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hrgmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jmlhmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nmsnack, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nmminuman, 0, 110, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hrgminuman, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeja, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namapel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ttltunai, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ttlkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(metode)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DineIn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(takeaway, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnjumlah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(16, 16, 16))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(namapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(namamakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmlhmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntambahmakan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nmminuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgminuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmlhminuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntambahminum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nmsnack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgsnack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmlhsnack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambahsnack)
                    .addComponent(btnhapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ttltunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ttlkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnjumlah)
                    .addComponent(btncetak))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnreset)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(metode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(takeaway)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DineIn)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomejaActionPerformed

    private void namapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapelActionPerformed

    private void namamakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namamakananActionPerformed
        // TODO add your handling code here:
        pilihan =(String)namamakanan.getSelectedItem();
        switch (pilihan){
            case "Nasi Pecel":
            Harga_makanan = 7000;
            break;
            
            case "Nasi Campur":
            Harga_makanan = 10000;
            break;
            
            case "Ayam Geprek":
            Harga_makanan = 10000;
            break;
            
            case "Nasi Padang":
            Harga_makanan = 15000;
            break;
    
            case "Rendang":
            Harga_makanan = 5000;
            break;
    
            case "Tidak Ada":
            Harga_makanan = 0;
            break;
        }
        hrgmakanan.setText(""+Integer.toString (Harga_makanan));
    }//GEN-LAST:event_namamakananActionPerformed

    private void hrgmakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgmakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgmakananActionPerformed

    private void jmlhmakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlhmakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlhmakananActionPerformed

    private void nmminumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmminumanActionPerformed
        // TODO add your handling code here:
         pilihan =(String)nmminuman.getSelectedItem();
        switch (pilihan){
            case "Es Jeruk":
            Harga_minuman = 3000;
            break;
            
            case "Es Campur":
            Harga_minuman = 7000;
            break;
            
            case "Es Teh":
            Harga_minuman = 3000;
            break;
            
            case "Kopi":
            Harga_minuman = 3000;
            break;
    
            case "Teh Hangat":
            Harga_minuman = 3000;
            break;
    
            case "Tidak Ada":
            Harga_minuman = 0;
            break;
        }
        hrgminuman.setText(""+Integer.toString (Harga_minuman));
    }//GEN-LAST:event_nmminumanActionPerformed

    private void hrgminumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgminumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgminumanActionPerformed

    private void jmlhminumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlhminumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlhminumanActionPerformed

    private void btntambahmakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahmakanActionPerformed
        // TODO add your handling code here:String  Nama_Costumer = (String) Namamakanan.getSelectedItem();
        String  Nama_Pelanggan = (String) namamakanan.getSelectedItem();
       int Harga_makanan = Integer.parseInt (hrgmakanan.getText());
       int QTY = Integer.parseInt(jmlhmakanan.getText());
       int Harga_total = Harga_makanan * QTY;
       
       DefaultTableModel tbl = (DefaultTableModel) tabelpesanan.getModel();
       
       tbl.addRow(new Object[]{
           Nama_Pelanggan,
           QTY,
           "Rp. "+ Harga_makanan,
           "Rp. "+ Harga_total
       });
       
       int TotalHarga =0;
       for(int i=0; i<tabelpesanan.getRowCount();i++){
           TotalHarga += Integer.parseInt(tabelpesanan.getValueAt(i, 3).toString().substring(4));
       }
       total.setText ("Rp. "+ TotalHarga);      
    }//GEN-LAST:event_btntambahmakanActionPerformed

    private void btntambahminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahminumActionPerformed
        // TODO add your handling code here:
        String  Nama_Pelanggan = (String) nmminuman.getSelectedItem();
       int Harga_minuman = Integer.parseInt (hrgminuman.getText());
       int QTY = Integer.parseInt(jmlhminuman.getText());
       int Harga_total = Harga_minuman * QTY;
       
       DefaultTableModel tbl = (DefaultTableModel) tabelpesanan.getModel();
       
        tbl.addRow(new Object[]{
           Nama_Pelanggan,
           QTY,
           "Rp. "+ Harga_minuman,
           "Rp. "+ Harga_total
       });
       
        int TotalHarga =0;
       for(int i=0; i<tabelpesanan.getRowCount();i++){
           TotalHarga += Integer.parseInt(tabelpesanan.getValueAt(i, 3).toString().substring(4));
       }
       total.setText ("Rp. "+ TotalHarga); 
    }//GEN-LAST:event_btntambahminumActionPerformed

    private void nmsnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmsnackActionPerformed
        // TODO add your handling code here:
        pilihan =(String)nmsnack.getSelectedItem();
        switch (pilihan){
            case "Kerupuk":
            Harga_snack = 1000;
            break;
    
            case "Lontong":
            Harga_snack = 1000;
            break;
            
            case "Peyek":
            Harga_snack = 1000;
            break;
    
            case "Tidak Ada":
            Harga_snack = 0;
            break;
        }
         hrgsnack.setText(""+Integer.toString (Harga_snack));
    }//GEN-LAST:event_nmsnackActionPerformed

    private void hrgsnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgsnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgsnackActionPerformed

    private void jmlhsnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlhsnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlhsnackActionPerformed

    private void btntambahsnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahsnackActionPerformed
        // TODO add your handling code here:
        String  Nama_Pelanggan = (String) nmsnack.getSelectedItem();
       int Harga_Snack = Integer.parseInt (hrgsnack.getText());
       int QTY = Integer.parseInt(jmlhsnack.getText());
       int Harga_total = Harga_Snack * QTY;
       
       DefaultTableModel tbl = (DefaultTableModel) tabelpesanan.getModel();
       
       tbl.addRow(new Object[]{
           Nama_Pelanggan,
           QTY,
           "Rp. "+ Harga_Snack,
           "Rp. "+ Harga_total
       });
       
       int TotalHarga =0;
       for(int i=0; i<tabelpesanan.getRowCount();i++){
           TotalHarga += Integer.parseInt(tabelpesanan.getValueAt(i, 3).toString(). substring(4));
       }
       total.setText ("Rp. "+ TotalHarga); 
    }//GEN-LAST:event_btntambahsnackActionPerformed

    private void DineInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DineInActionPerformed
        // TODO add your handling code here:
        if (DineIn.isSelected()){
            metode.setText("Dine In");
        }
    }//GEN-LAST:event_DineInActionPerformed

    private void takeawayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeawayActionPerformed
        // TODO add your handling code here:
        if (takeaway.isSelected()){
            metode.setText("Take Away");
        }
    }//GEN-LAST:event_takeawayActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
         int sub_total = 0;
     for (int i = 0; i<tabelpesanan.getRowCount(); i++){
          sub_total+= Integer.parseInt((String) tabelpesanan.getValueAt(i,4).toString().replace(".",""));
     }
     total.setText(nf.Format(sub_total));
    }//GEN-LAST:event_totalActionPerformed

    private void ttltunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttltunaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttltunaiActionPerformed

    private void ttlkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttlkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttlkembaliActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pembayaranActionPerformed

    private void btnjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjumlahActionPerformed
        // TODO add your handling code here:
        int TotalHarga = Integer.parseInt(total.getText().substring(4));
        int Tunai = Integer.parseInt(ttltunai.getText());
        int Kembalian = Tunai - TotalHarga;
        ttlkembali.setText("Rp. "+ Kembalian);
    }//GEN-LAST:event_btnjumlahActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        namapel.setText("");
        namamakanan.setSelectedItem("None");
        jmlhmakanan.setText("");
        nmminuman.setSelectedItem("None");
        jmlhminuman.setText("");
        nmsnack.setSelectedItem("None");
        jmlhsnack.setText("");
        total.setText("");
        ttltunai.setText("");
        pembayaran.setSelectedItem("None");
        ttlkembali.setText("");
     
     DefaultTableModel tbl = (DefaultTableModel) tabelpesanan.getModel();
        for (int i = 0; i<= tabelpesanan.getRowCount(); i++){
            tbl.removeRow(all);  
        }
    }//GEN-LAST:event_btnresetActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        NamaPelanggan = namapel.getText();
        Nomeja = nomeja.getText();
        if (DineIn.isSelected()){
            DT = "Dine in";
        }else{
            DT = "Take Away";            
        }
        Makanan = (String) namamakanan.getSelectedItem();
        HargaMakanan = hrgmakanan.getText();
        JumlahMakanan = jmlhmakanan.getText();
        Minuman = (String) nmminuman.getSelectedItem();
        HargaMinuman = hrgminuman.getText();
        JumlahMinuman = jmlhminuman.getText();
        Snack = (String) nmsnack.getSelectedItem();
        HargaSnack = hrgsnack.getText();
        JumlahSnack = jmlhsnack.getText();
        TotalHarga = total.getText();
        Tunai = ttltunai.getText();
        Kembali = ttlkembali.getText();
        Pembayaran = (String) pembayaran.getSelectedItem();
        Metode = metode.getText();
        Struukkk st = new Struukkk(NamaPelanggan, Nomeja, DT, Makanan, HargaMakanan, JumlahMakanan, Minuman, HargaMinuman, JumlahMinuman, Snack, HargaSnack, JumlahSnack, TotalHarga, Tunai, Kembali, Pembayaran, Metode);
        st.setVisible(true);
        dispose();
    }//GEN-LAST:event_btncetakActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelpesanan.getModel();
        int row = tabelpesanan.getSelectedRow();
        model.removeRow(row);
        total.setText("");
        ttlkembali.setText("");    
    }//GEN-LAST:event_btnhapusActionPerformed

    private void metodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodeActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DineIn;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnjumlah;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntambahmakan;
    private javax.swing.JButton btntambahminum;
    private javax.swing.JButton btntambahsnack;
    private javax.swing.JTextField hrgmakanan;
    private javax.swing.JTextField hrgminuman;
    private javax.swing.JTextField hrgsnack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlhmakanan;
    private javax.swing.JTextField jmlhminuman;
    private javax.swing.JTextField jmlhsnack;
    private javax.swing.JTextField metode;
    private javax.swing.JComboBox<String> namamakanan;
    private javax.swing.JTextField namapel;
    private javax.swing.JComboBox<String> nmminuman;
    private javax.swing.JComboBox<String> nmsnack;
    private javax.swing.JTextField nomeja;
    private javax.swing.JComboBox<String> pembayaran;
    private javax.swing.JTable tabelpesanan;
    private javax.swing.JCheckBox takeaway;
    private javax.swing.JTextField total;
    private javax.swing.JTextField ttlkembali;
    private javax.swing.JTextField ttltunai;
    // End of variables declaration//GEN-END:variables
}
