/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restosalero2;

/**
 *
 * @author 058 Ernika Frevita Ayu Septiani
 *         051 Sefni Marcella 
 *         PTI B 2022
 */
public class Struukkk extends javax.swing.JFrame {

    /**
     * Creates new form Struukkk
     */
    String NamaPelanggan;
    String Nomeja;
    String DT;
    String Makanan;
    String HargaMakanan;
    String JumlahMakanan;
    String Minuman;
    String HargaMinuman;
    String JumlahMinuman;
    String Snack;
    String HargaSnack;
    String JumlahSnack;
    String TotalHarga;
    String Tunai;
    String Kembali;
    String Pembayaran;
    String Table;
    String Metode;
    public Struukkk(String NamaPelanggan, String Nomeja, String DT, String Makanan, String HargaMakanan, String JumlahMakanan, String Minuman, String HargaMinuman, String JumlahMinuman, String Snack, String HargaSnack, String JumlahSnack,  String TotalHarga, String Tunai, String Kembali, String Pembayaran, String Metode) {
        initComponents();
        this.NamaPelanggan = NamaPelanggan;
        this.Nomeja = Nomeja;
        this.DT = DT;
        this.Makanan = Makanan;
        this.HargaMakanan = HargaMakanan;
        this.JumlahMakanan = JumlahMakanan;
        this.Minuman = Minuman;
        this.HargaMinuman = HargaMinuman;
        this.JumlahMinuman = JumlahMinuman;
        this.Snack = Snack;
        this.HargaSnack = HargaSnack;
        this.JumlahSnack = JumlahSnack;
        this.TotalHarga = TotalHarga;
        this.Tunai = Tunai;
        this.Kembali = Kembali;
        this.Pembayaran = Pembayaran;
        this.Metode = Metode;
        struukkk.setText(struukkk.getText()+"-------------------------------------------------------------------\n");
        struukkk.setText(struukkk.getText()+"                         RESTO SALERO                            \n");
        struukkk.setText(struukkk.getText()+"                          Jl. Smea No.31                           \n");
        struukkk.setText(struukkk.getText()+"                          085574109340                             \n");
        struukkk.setText(struukkk.getText()+"-------------------------------------------------------------------\n");
        
        struukkk.setText(struukkk.getText()+" Nama Pelanggan : " + this.NamaPelanggan + "\n");
        struukkk.setText(struukkk.getText()+" Nomor Meja \t : " + this.Nomeja + "\n");
        struukkk.setText(struukkk.getText()+" Makanan : " + this.Makanan + "\n");
        struukkk.setText(struukkk.getText()+" Harga Makanan : " + this.HargaMakanan + "\n");
        struukkk.setText(struukkk.getText()+" Jumlah Makanan : " + this.JumlahMakanan + "\n");
        struukkk.setText(struukkk.getText()+" Minuman : " + this.Minuman + "\n");
        struukkk.setText(struukkk.getText()+" Harga Minuman : " + this.HargaMinuman + "\n");
        struukkk.setText(struukkk.getText()+" Jumlah Minuman : " + this.JumlahMinuman + "\n");
        struukkk.setText(struukkk.getText()+" Snack : " + this.Snack + "\n");
        struukkk.setText(struukkk.getText()+" Harga Snack : " + this.HargaSnack + "\n");
        struukkk.setText(struukkk.getText()+" Jumlah Snack : " + this.JumlahSnack + "\n");
        struukkk.setText(struukkk.getText()+" Total Harga\t : " + this.TotalHarga + "\n");
        struukkk.setText(struukkk.getText()+" Tunai\t : " + this.Tunai + "\n");
        struukkk.setText(struukkk.getText()+" Kembalian\t : " + this.Kembali + "\n");
        struukkk.setText(struukkk.getText()+" Pembayaran\t : " + this.Pembayaran + "\n");
        struukkk.setText(struukkk.getText()+" Metode Pemesanan : " + this.Metode + "\n");
        
        struukkk.setText(struukkk.getText()+"====================================\n");
        
        struukkk.setText(struukkk.getText()+"********************** Terimakasih ******************\n");
    }


    Struukkk() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        struukkk = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        struukkk.setEditable(false);
        struukkk.setColumns(20);
        struukkk.setRows(5);
        struukkk.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                struukkkAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(struukkk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void struukkkAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_struukkkAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_struukkkAncestorAdded

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Struukkk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Struukkk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Struukkk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Struukkk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Struukkk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea struukkk;
    // End of variables declaration//GEN-END:variables
}
